application:
  title: "E2E Demo"
  version: 1.0

app:
  # For AP
  topology-keys: aws.ap-southeast-1.ap-southeast-1c
  initial-ysql-host: 127.0.0.1
  region: AP
  security:
    jwt:
      secret: cccccclvkgnllrhrngucjbivrehvjcnkfvfihildhfcg
      expiry: 86400
  cors:
    allowed_origins: http://localhost:3000/
    max_age: 3600

spring:
  datasource:
    driver-class-name: com.yugabyte.Driver
    url: 'jdbc:yugabytedb://${app.initial-ysql-host}:5433/yugabyte?load-balance=true&topology-keys=${app.topology-keys}'
    username: yugabyte
  data:
    rest:
      base-path: /api/v1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    web: debug
    sql: debug

